# Generated by Django 3.0.5 on 2021-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('L', 'Laptop'), ('TW', 'Top wear'), ('BW', 'Bottom wear')], max_length=2),
        ),
    ]
